name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/flask-app:latest .

      - name: Push Docker image
        run: docker push your-dockerhub-username/flask-app:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Останавливаем и удаляем старый контейнер
            docker stop flask-container || true
            docker rm flask-container || true

            # Скачиваем новый образ
            docker pull your-dockerhub-username/flask-app:latest

            # Запускаем новый контейнер
            docker run -d -p 5000:5000 --name flask-container your-dockerhub-username/flask-app:latest
