name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Вход в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Сборка и публикация Docker-образа
        run: |
          docker build -t mydockerhubuser/flask-app:latest .
          docker push mydockerhubuser/flask-app:latest

      - name: Развёртывание на сервере
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull mydockerhubuser/flask-app:latest
            docker stop flask-container || true
            docker rm flask-container || true
            docker run -d -p 5000:5000 --name flask-container mydockerhubuser/flask-app:latest
